language: node_js

node_js:
- 'node'

os:
- linux
dist: trusty # using Ubuntu 14.04.5 LTS

branches:
  only:
  - master
  - /v?[0-9]+\.[0-9]+\.[0-9]+(.*)?/

env:
  global:
    - ISPRODTAG=^v?[0-9]+\.[0-9]+\.[0-9]+$

install:
- sudo apt-get install libsecret-1-dev
- npm install -g vsce
- npm install

script:
- jq --version
- if [[ $TRAVIS_TAG =~ $ISPRODTAG ]]; then jq '.codeGenConfigUrl = "https://aka.ms/iot-codegen-cli-for-workbench"' package.json > package_tmp.json; else jq '.codeGenConfigUrl = "https://aka.ms/iot-codegen-cli-for-workbench-staging"' package.json > package_tmp.json; fi
- mv package_tmp.json package.json
- tsc --version
- gts --version
- gts check
- node genAiKey.js
- vsce package

deploy:
  # deploy to github release
  - provider: releases
    api_key: $GIT_TOKEN
    file_glob: true
    file: "*.vsix"
    skip_cleanup: true
    on:
      tags: true
      all_branches: true
  # deploy to vscode extension market
  - provider: script  
    script: vsce publish -p $VSCE_TOKEN --packagePath *.vsix
    skip_cleanup: true
    on:
      tags: true
      all_branches: true
      # if it's a PROD tag (something like 1.0.0), then publish extension to market.
      condition: "$TRAVIS_TAG =~ $ISPRODTAG"